import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException; // Die Klasen importieren

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erdsma14
 */
public class JPrjkt_erdis extends javax.swing.JFrame { //Um eine GUI-Applikation zu schreiben, erweitern wir die JFrame-Klasse
    Connection con=null; //Verbindung zum Datenbank
    PreparedStatement stmt_selectAll=null; //PreparedStatements fur SELECT
    ResultSet res_selectAll=null; //ResultSet fur SELECT
    PreparedStatement stmt_add=null; //PreparedStatements fur INSERT, ein Movie zu addieren
    PreparedStatement stmt_update=null; //PreparedStatement fur updating einer Movie
    PreparedStatement stmt_delete=null; //PreparedStatement fur deleting ein Movie
    
            
    
    public JPrjkt_erdis() { // Konstruktor 
        initComponents(); //Komponente initialisieren
        try { // Uberprufen ob die DB geladen werden konnen.
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            System.out.println("Datenbankdriver konnte nicht geladen werden");
            javax.swing.JOptionPane.showMessageDialog(this, "Datenbankdriver konnte nicht geladen werden");
            System.exit(1);            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this id. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabelServer = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jButtonConnect = new javax.swing.JButton();
        jButtonDisconnect = new javax.swing.JButton();
        jTextFieldlocalhost = new javax.swing.JTextField();
        jTextField3306 = new javax.swing.JTextField();
        jLabelid = new javax.swing.JLabel();
        jLabelVorname = new javax.swing.JLabel();
        jLabelNachname = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jTextFieldVorname = new javax.swing.JTextField();
        jTextFieldNachname = new javax.swing.JTextField();
        jButtonRechts = new javax.swing.JButton();
        jButtonLinks = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelDatabase = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldDtbase = new javax.swing.JTextField();
        jTextFieldusername = new javax.swing.JTextField();
        jTextFieldpassword = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelServer.setText("Server");

        jLabelPort.setText("Port");

        jButtonConnect.setText("Connect");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jButtonDisconnect.setText("Disconnect");
        jButtonDisconnect.setEnabled(false);
        jButtonDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisconnectActionPerformed(evt);
            }
        });

        jTextFieldlocalhost.setText("localhost");
        jTextFieldlocalhost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlocalhostActionPerformed(evt);
            }
        });

        jTextField3306.setText("3306");
        jTextField3306.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3306ActionPerformed(evt);
            }
        });

        jLabelid.setText("id:");

        jLabelVorname.setText("Vorname:");

        jLabelNachname.setText("Nachname:");

        jTextFieldid.setEditable(false);
        jTextFieldid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidActionPerformed(evt);
            }
        });

        jTextFieldVorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVornameActionPerformed(evt);
            }
        });

        jButtonRechts.setText(">");
        jButtonRechts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechtsActionPerformed(evt);
            }
        });

        jButtonLinks.setText("<");
        jButtonLinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLinksActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelDatabase.setText("Database");

        jLabelUsername.setText("Username");

        jLabelPassword.setText("Password");

        jTextFieldDtbase.setText("3by_erdismajlaj_fussball");
        jTextFieldDtbase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDtbaseActionPerformed(evt);
            }
        });

        jTextFieldusername.setText("root");
        jTextFieldusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldusernameActionPerformed(evt);
            }
        });

        jTextFieldpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpasswordActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add Person");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelServer)
                            .addComponent(jLabelPort))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldlocalhost, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3306, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelDatabase)
                            .addComponent(jLabelUsername))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDtbase, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldusername, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVorname)
                            .addComponent(jLabelid)
                            .addComponent(jLabelNachname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonDisconnect))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldVorname)
                                    .addComponent(jTextFieldNachname)
                                    .addComponent(jTextFieldid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonLinks)
                                        .addGap(37, 37, 37)
                                        .addComponent(jButtonClear)
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButtonAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jButtonRechts)
                                        .addGap(29, 29, 29))
                                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonDisconnect))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelServer)
                            .addComponent(jTextFieldlocalhost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDatabase)
                            .addComponent(jTextFieldDtbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConnect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelPort)
                                .addComponent(jTextField3306, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelUsername)
                                .addComponent(jTextFieldusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelid)
                            .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete)
                            .addComponent(jButtonAdd)))
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVorname))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNachname)
                            .addComponent(jTextFieldNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRechts)
                            .addComponent(jButtonClear)
                            .addComponent(jButtonLinks))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3306ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3306ActionPerformed
        // TODO add your handling id here:
    }//GEN-LAST:event_jTextField3306ActionPerformed

    private void jTextFieldlocalhostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlocalhostActionPerformed
        // TODO add your handling id here:
    }//GEN-LAST:event_jTextFieldlocalhostActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        try { //establish connection
            con=DriverManager.getConnection("jdbc:mysql://"+jTextFieldlocalhost.getText()+":"+jTextField3306.getText()+"/"+jTextFieldDtbase.getText(),jTextFieldusername.getText(),jTextFieldpassword.getText());
            //disable und enable components with respect to connected or not connected
            jButtonConnect.setEnabled(false);
            jTextFieldlocalhost.setEnabled(false);
            jButtonDisconnect.setEnabled(true);
        } catch (SQLException ex) { //error message can not connect
            System.out.println("Connection konnte nicht gemacht werden");
            javax.swing.JOptionPane.showMessageDialog(this, "Connection konnte nicht gemacht werden");
        }

        try{ 
            
            stmt_selectAll = con.prepareStatement("SELECT * FROM persons");
            stmt_add = con.prepareStatement("INSERT INTO persons (Vorname, Nachname) VALUES (?, ?)");
            stmt_update = con.prepareStatement("UPDATE persons SET Vorname = ?, Nachname = ? WHERE id = ?");
            stmt_delete = con.prepareStatement("DELETE FROM persons WHERE id = ?");
            res_selectAll = stmt_selectAll.executeQuery();
            if(res_selectAll.next()){ 
                // Resultaten von ResultSet nehmen
                int id = res_selectAll.getInt("id");
                String vorname = res_selectAll.getString("Vorname");
                String nachname = res_selectAll.getString("Nachname");
               
                // Resultaten die genommen wurden, in Variablen speichern, Textfields mit Werten einfuegen
                jTextFieldid.setText(""+id);
                jTextFieldVorname.setText(vorname);
                jTextFieldNachname.setText(nachname);  
            }
        }catch(SQLException ex){ //error message can not connect
            System.out.println("SELECT konnte nicht gemacht werden");
            javax.swing.JOptionPane.showMessageDialog(this, "SELECT konnte nicht gemacht werden");
        }     
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jButtonDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisconnectActionPerformed
        try { //establish disconnection
            con.close();
            jButtonConnect.setEnabled(true);
            jTextFieldlocalhost.setEnabled(true);
            jButtonDisconnect.setEnabled(false);
        } catch (SQLException ex) { // Die Verbindung kann mit dem DB nicht geschlossen werden 
            System.out.println("Verbindung mit dem Datenbankserver konnte nicht geschlossen werden");
            javax.swing.JOptionPane.showMessageDialog(this, "Datenbankdriver konnte nicht geschlossen werden");
        }
    }//GEN-LAST:event_jButtonDisconnectActionPerformed

    private void jTextFieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidActionPerformed
        // TODO add your handling id here:
    }//GEN-LAST:event_jTextFieldidActionPerformed

    private void jButtonRechtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechtsActionPerformed
        try{ //Resultaten von ResultSet nehmen
            if(res_selectAll.next()){ //hier werden die Movies rechts verschieben
                int id = res_selectAll.getInt("id");
                String vorname = res_selectAll.getString("vorname");
                String nachname = res_selectAll.getString("nachname");
                jTextFieldid.setText(""+id);
                jTextFieldVorname.setText(vorname);
                jTextFieldNachname.setText(nachname);
            }else{ //den Zeilenzeiger setzen vor das erste Element
                res_selectAll.beforeFirst();
            }
        }catch(SQLException ex){ //SELECT kann nicht gemacht werden
            System.out.println("SELECT konnte nicht gemacht werden");
            javax.swing.JOptionPane.showMessageDialog(this, "SELECT konnte nicht gemacht werden");
        }
    }//GEN-LAST:event_jButtonRechtsActionPerformed

    private void jButtonLinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLinksActionPerformed
         try{ //Resultaten von ResultSet nehmen
            if(res_selectAll.previous()){ //hier werden die Movies links verschieben
                int id = res_selectAll.getInt("id");
                String vorname = res_selectAll.getString("vorname");
                String nachname = res_selectAll.getString("nachname");
                jTextFieldid.setText(""+id);
                jTextFieldVorname.setText(vorname);
                jTextFieldNachname.setText(nachname); 
            }else{ //den Zeilenzeiger setzen nach das erste Element
                res_selectAll.afterLast();
            }
        }catch(SQLException ex){ //SELECT kann nicht gemacht werden
            System.out.println("SELECT konnte nicht gemacht werden");
            javax.swing.JOptionPane.showMessageDialog(this, "SELECT konnte nicht gemacht werden");
        }          
    }//GEN-LAST:event_jButtonLinksActionPerformed

    private void jTextFieldusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldusernameActionPerformed
        // TODO add your handling id here:
    }//GEN-LAST:event_jTextFieldusernameActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldVorname.setText(""); // TextField von Titel leer lassen
        jTextFieldNachname.setText(""); // TextField von Rating leer lassen
        jTextFieldid.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try{
            stmt_update.setString(1, jTextFieldVorname.getText());
            stmt_update.setString(2, jTextFieldNachname.getText());
            stmt_update.setInt(3, Integer.parseInt(jTextFieldid.getText()));
            //stmt_add.executeUpdate();
            int rows_changed = stmt_update.executeUpdate();
            res_selectAll = stmt_selectAll.executeQuery();
            if(rows_changed > 0){
                javax.swing.JOptionPane.showMessageDialog(this, "Es ist updatet");
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Es ist nicht updatet");
            }    
        }catch(SQLException ex) {
            System.out.println("Es ist nicht updatet");    
            javax.swing.JOptionPane.showMessageDialog(this, "Es ist nicht updatet");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try{
            stmt_delete.setInt(1, Integer.parseInt(jTextFieldid.getText()));
            int rows_changed = stmt_delete.executeUpdate();
            res_selectAll = stmt_selectAll.executeQuery();
            if(rows_changed > 0){
                javax.swing.JOptionPane.showMessageDialog(this, "Es ist nicht mehr da");
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Es ist da");
            }  
        }catch(SQLException ex) {
            System.out.println("Es ist da");    
            javax.swing.JOptionPane.showMessageDialog(this, "Es ist da");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpasswordActionPerformed
        // TODO add your handling id here:
    }//GEN-LAST:event_jTextFieldpasswordActionPerformed

    private void jTextFieldDtbaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDtbaseActionPerformed
        // TODO add your handling id here:
    }//GEN-LAST:event_jTextFieldDtbaseActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
         try{
        stmt_add.setString(1,jTextFieldVorname.getText());
        stmt_add.setString(2,jTextFieldNachname.getText());
             System.out.println(stmt_add);
        int rows_changed = stmt_add.executeUpdate();
        res_selectAll = stmt_selectAll.executeQuery();
        if(rows_changed > 0){
            javax.swing.JOptionPane.showMessageDialog(this, "Alles OKAY");
        }else{
        javax.swing.JOptionPane.showMessageDialog(this, "Leider, nicht okay");
        }
            
    }catch(SQLException ex) {
        System.out.println("Leider, nicht okay");    
            javax.swing.JOptionPane.showMessageDialog(this, "Leider, nicht okay");
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldVornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVornameActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting id (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPrjkt_erdis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPrjkt_erdis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPrjkt_erdis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPrjkt_erdis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPrjkt_erdis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDisconnect;
    private javax.swing.JButton jButtonLinks;
    private javax.swing.JButton jButtonRechts;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDatabase;
    private javax.swing.JLabel jLabelNachname;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelServer;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelVorname;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField3306;
    private javax.swing.JTextField jTextFieldDtbase;
    private javax.swing.JTextField jTextFieldNachname;
    private javax.swing.JTextField jTextFieldVorname;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldlocalhost;
    private javax.swing.JTextField jTextFieldpassword;
    private javax.swing.JTextField jTextFieldusername;
    // End of variables declaration//GEN-END:variables
}
